PREFIX ns1: <http://www.w3.org/1999/xhtml/vocab#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ns1: <localhost:3030/>

SELECT ?sujet ?latitude ?altitude
WHERE {
  ?sujet ns1:lat ?latitude .
  ?sujet ns1:alt ?altitude .
FILTER (xsd:float(?latitude) > 50 && xsd:float(?altitude) > 90)
}
