PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dbp:	<http://dbpedia.org/property/>
PREFIX ns1: <http://dbpedia.org/ontology/>
PREFIX ex: <http://example.org/>



SELECT ?name ?type
WHERE {
    SERVICE <http://localhost:3030/turtle_data/query> {
        ?dinosaur ex:commonProperty ?commonValue.
        ?dinosaur ns1:name ?name.
        ?dinosaur ns1:type ?type.
    }

    SERVICE <http://localhost:3030/birds_united_states/query> {
        ?bird ex:commonProperty ?commonValue.
        ?bird ns1:name ?name.
        ?bird ns1:type ?type.
    }
}
